apiVersion: apps/v1
kind: Deployment
metadata:
  name: configapp
spec:
  selector:
    matchLabels:
      app: configapp
  replicas: 3
  template:
    metadata:
      labels:
        app: configapp
    spec:
      containers:
      - name: configapp
        image: nanajanashia/argocd-app:1.1
        ports:
        - containerPort: 8080